//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetWebFormsLoadTime.Pages {
    
    
    public partial class Complex {
        
        /// <summary>
        /// firstUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetWebFormsLoadTime.UserControls.FirstUserControl firstUserControl;
        
        /// <summary>
        /// secondUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetWebFormsLoadTime.UserControls.SecondUserControl secondUserControl;
        
        /// <summary>
        /// loadTimeUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetWebFormsLoadTime.UserControls.LoadTimeUserControl loadTimeUserControl;
    }
}
